development:
  access_key_id: AKIAIPEUBU2GWBTXSYTA
  secret_code: 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

production:
  access_key_id: AKIAIPEUBU2GWBTXSYTA
  secret_code: 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